### ISSUE TITLE
Add LICENSE?

### ISSUE THREAD

**Issue by mik3y** [huming2207/esp-totp#1]
Hi Jackson! Thanks for making this library available. I plan to use it my small project here: https://github.com/mik3y/esp32-ble-pinpad

I wanted to ask you what the license and copyright are, so I can properly credit it. Perhaps MIT, to match the upstream `c_otp` library? Thanks!

**Comment by huming2207** [comment]
Hi @mik3y ,

Thanks for your advice. I've added the MIT license here: 8ea4ee714301af1de4532eda706ba055e4684663

Regards,
Jackson

**Comment by mik3y** [comment]
Ah, fantastic! Updating my project to incorporate. Thanks again for the lovely reference code.
